name: Build
  
on:
  push:
    branches:
      - auto2

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup build constants
        id: constants
        run: |
          export TZ=Europe/Warsaw
          date=$(date +'%Y-%m-%d %H:%M')
          
          echo "::set-output name=release_name::$date"
          echo "::set-output name=release_tag::${date//[^0-9]/.}"

      - uses: actions/checkout@v2
        
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: ${{ steps.constants.outputs.release_tag }}
          RELEASE_NAME: ${{ steps.constants.outputs.release_name }}
