name: Build
  
on:
  push:
    branches:
      - auto2

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup build constants
        id: constants
        run: |
          export TZ=Europe/Warsaw
          date=$(date +'%Y-%m-%d %H:%M')
          
          echo "::set-output name=release_name::$date"
          echo "::set-output name=release_tag::v${date//[^0-9]/.}"

      - uses: actions/checkout@v2
        
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: ${{ steps.constants.outputs.release_tag }}
          RELEASE_NAME: ${{ steps.constants.outputs.release_name }}
          
#       - name: Create a Release
#         uses: actions/create-release@v1.1.4
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ steps.constants.outputs.release_tag }}
#           release_name: ${{ steps.constants.outputs.release_name }}
          
      - name: Create Release
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('environment', process.versions);

            const fs = require('fs').promises;

            const { repo: { owner, repo }, sha } = context;
            console.log({ owner, repo, sha });

            const release = await github.repos.createRelease({
              owner, repo,
              tag_name: process.env.RELEASE_TAG,
              draft: false,
              target_commitish: sha
            });

            console.log('created release', { release });

            for (let file of await fs.readdir('.')) {
              if (file.match(/Makefile/)) {
                // do whatever filtering you want here, I'm just uploading all the files
                console.log('uploading', file);

                await github.repos.uploadReleaseAsset({
                  owner, repo,
                  release_id: release.data.id,
                  name: file,
                  data: await fs.readFile(`./${file}`)
                });
              }
            }
        env:
          RELEASE_TAG: ${{ steps.constants.outputs.release_tag }}
          RELEASE_NAME: ${{ steps.constants.outputs.release_name }}
